-- NewsFramer — source seed data (RSS / scrape registry).
-- Run AFTER sql/schema.sql. These are the operator's default sources; tune freely — the
-- `weight` values are editorial defaults a reuser can change. Excludes the 4 inactive football
-- rows and the dead 'Reuters Technology' feed (per the live-DB reference).
-- Bundles (category): crypto, cybersecurity, geopolitics, investigative, pakistan, tech, vc.

insert into sources (name, category, weight, source_type, has_rss, rss_url, site_url, language, fetch_mode, fetch_window_hours, region, groundnews_publication_bias, groundnews_factuality, scrape_days, active) values
  ('Bankless', 'crypto', 1, 'blog', true, 'https://banklesshq.com/rss', 'https://banklesshq.com', 'en', 'rss', 24, null, null, null, null, true),
  ('CoinDesk', 'crypto', 1, 'news', true, 'https://www.coindesk.com/arc/outboundfeeds/rss/', 'https://coindesk.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Cointelegraph', 'crypto', 0.9, 'news', true, 'https://cointelegraph.com/rss', 'https://cointelegraph.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Decrypt', 'crypto', 0.9, 'news', true, 'https://decrypt.co/feed', 'https://decrypt.co', 'en', 'rss', 24, null, null, null, null, true),
  ('Delphi Digital', 'crypto', 0.9, 'research', false, null, 'https://delphidigital.io', 'en', 'browser_required', 168, null, null, null, null, true),
  ('Messari', 'crypto', 1, 'research', true, 'https://messari.io/rss', 'https://messari.io', 'en', 'rss', 24, null, null, null, null, true),
  ('The Block', 'crypto', 1, 'news', true, 'https://www.theblock.co/rss.xml', 'https://theblock.co', 'en', 'rss', 24, null, null, null, null, true),
  ('BleepingComputer', 'cybersecurity', 1, 'news', true, 'https://www.bleepingcomputer.com/feed/', 'https://www.bleepingcomputer.com', 'en', 'rss', 24, 'Global', null, null, null, true),
  ('Dark Reading', 'cybersecurity', 0.9, 'news', true, 'https://www.darkreading.com/rss.xml', 'https://www.darkreading.com', 'en', 'rss', 24, 'Global', null, null, null, true),
  ('KrebsOnSecurity', 'cybersecurity', 0.9, 'blog', true, 'https://krebsonsecurity.com/feed/', 'https://krebsonsecurity.com', 'en', 'rss', 336, 'Global', null, null, null, true),
  ('The Hacker News', 'cybersecurity', 1, 'news', true, 'https://feeds.feedburner.com/TheHackersNews', 'https://thehackernews.com', 'en', 'rss', 24, 'Global', null, null, null, true),
  ('Al Jazeera', 'geopolitics', 1, 'news', true, 'https://www.aljazeera.com/xml/rss/all.xml', 'https://aljazeera.com', 'en', 'rss', 24, null, 'left', 'High', null, true),
  ('Associated Press', 'geopolitics', 1, 'news', true, 'https://news.google.com/rss/search?q=site:apnews.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'https://apnews.com', 'en', 'rss', 24, null, 'left', 'High', null, true),
  ('BBC World', 'geopolitics', 1, 'news', true, 'http://feeds.bbci.co.uk/news/world/rss.xml', 'https://bbc.com/news/world', 'en', 'rss', 24, null, 'center', 'High', null, true),
  ('CNN', 'geopolitics', 0.5, 'news', true, 'https://news.google.com/rss/search?q=site:cnn.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'https://cnn.com', 'en', 'rss', 24, null, 'left', 'Mixed', null, true),
  ('Heather Cox Richardson', 'geopolitics', 0.7, 'blog', true, 'https://heathercoxrichardson.substack.com/feed', 'https://heathercoxrichardson.substack.com', 'en', 'rss', 24, null, 'left', 'Mixed', null, true),
  ('Middle East Eye', 'geopolitics', 0.9, 'news', true, 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net', 'en', 'rss', 48, 'MENA', 'left', 'High', null, true),
  ('Middle East Monitor', 'geopolitics', 0.9, 'news', true, 'https://www.middleeastmonitor.com/feed/', 'https://www.middleeastmonitor.com', 'en', 'rss', 24, 'MENA', 'left', 'Mixed', null, true),
  ('New York Post', 'geopolitics', 0.5, 'news', true, 'https://nypost.com/feed/', 'https://nypost.com', 'en', 'rss', 24, null, 'right', 'Mixed', null, true),
  ('Noahpinion', 'geopolitics', 0.9, 'blog', true, 'https://noahpinion.substack.com/feed', 'https://noahpinion.substack.com', 'en', 'rss', 24, null, 'center', 'Mixed', null, true),
  ('Reuters', 'geopolitics', 1, 'news', true, 'https://news.google.com/rss/search?q=site:reuters.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'https://reuters.com', 'en', 'rss', 24, null, 'center', 'High', null, true),
  ('The Guardian', 'geopolitics', 1, 'news', true, 'https://www.theguardian.com/world/rss', 'https://www.theguardian.com', 'en', 'rss', 24, 'Europe', 'left', 'High', null, true),
  ('TRT Global', 'geopolitics', 0.8, 'news', false, null, 'https://www.trtworld.com/', 'en', 'browser_required', 24, 'MENA', 'left', 'Mixed', null, true),
  ('Zeteo', 'geopolitics', 0.7, 'news', true, 'https://zeteo.com/feed', 'https://zeteo.com', 'en', 'rss', 24, 'Global', 'left', 'Mixed', null, true),
  ('+972 Magazine', 'investigative', 0.9, 'news', true, 'https://www.972mag.com/feed/', 'https://www.972mag.com', 'en', 'rss', 48, 'MENA', null, null, null, true),
  ('Access Now', 'investigative', 0.7, 'research', true, 'https://www.accessnow.org/feed/', 'https://www.accessnow.org', 'en', 'rss', 720, 'Global', null, null, null, true),
  ('Amnesty Evidence Lab', 'investigative', 0.7, 'research', false, null, 'https://citizenevidence.org', 'en', 'browser_required', 168, 'Global', null, null, 'tue', true),
  ('Amnesty Security Lab', 'investigative', 0.8, 'research', true, 'https://securitylab.amnesty.org/feed/', 'https://securitylab.amnesty.org', 'en', 'rss', 720, 'Global', null, null, null, true),
  ('Bellingcat', 'investigative', 0.9, 'research', true, 'https://www.bellingcat.com/feed/', 'https://www.bellingcat.com', 'en', 'rss', 168, 'Global', null, null, null, true),
  ('Center for Spatial Technologies', 'investigative', 0.6, 'research', false, null, 'https://spatialtech.info/', 'en', 'browser_required', 336, 'Global', null, null, 'thu', true),
  ('Citizen Lab', 'investigative', 0.9, 'research', true, 'https://citizenlab.ca/feed/', 'https://citizenlab.ca', 'en', 'rss', 336, 'Global', null, null, null, true),
  ('EFF', 'investigative', 0.8, 'research', true, 'https://www.eff.org/rss/updates.xml', 'https://www.eff.org', 'en', 'rss', 48, 'Global', null, null, null, true),
  ('Forbidden Stories', 'investigative', 0.8, 'news', true, 'https://forbiddenstories.org/feed/', 'https://forbiddenstories.org', 'en', 'rss', 168, 'Global', null, null, null, true),
  ('Forensic Architecture', 'investigative', 0.8, 'research', true, 'https://forensicarchitecture.substack.com/feed', 'https://forensicarchitecture.org', 'en', 'rss', 720, 'Global', null, null, null, true),
  ('Google TAG', 'investigative', 0.7, 'research', true, 'https://cloudblog.withgoogle.com/topics/threat-intelligence/rss/', 'https://cloud.google.com/blog/topics/threat-intelligence', 'en', 'rss', 168, 'Global', null, null, null, true),
  ('TechNadu', 'investigative', 0.6, 'news', true, 'https://www.technadu.com/feed/', 'https://www.technadu.com', 'en', 'rss', 168, 'Global', null, null, null, true),
  ('The Intercept', 'investigative', 0.9, 'news', true, 'https://theintercept.com/feed/?rss', 'https://theintercept.com', 'en', 'rss', 48, 'Global', null, null, null, true),
  ('Dawn', 'pakistan', 1, 'news', true, 'https://www.dawn.com/feeds/home', 'https://dawn.com', 'en', 'rss', 24, 'South Asia', 'center', 'High', null, true),
  ('The Express Tribune', 'pakistan', 0.9, 'news', true, 'https://tribune.com.pk/feed/home', 'https://tribune.com.pk', 'en', 'rss', 24, 'South Asia', 'center', 'High', null, true),
  ('The News International', 'pakistan', 0.9, 'news', true, 'https://www.thenews.com.pk/rss/1/2', 'https://www.thenews.com.pk', 'en', 'rss', 24, 'South Asia', 'right', 'Mixed', null, true),
  ('Ars Technica', 'tech', 0.9, 'news', true, 'https://feeds.arstechnica.com/arstechnica/index', 'https://arstechnica.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Balaji Srinivasan', 'tech', 1, 'blog', true, 'https://balajis.com/rss', 'https://balajis.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Benedict Evans', 'tech', 1, 'blog', true, 'https://www.ben-evans.com/benedictevans/rss.xml', 'https://ben-evans.com', 'en', 'rss', 24, null, null, null, null, true),
  ('IEEE Spectrum', 'tech', 0.9, 'news', true, 'https://spectrum.ieee.org/feeds/feed.rss', 'https://spectrum.ieee.org', 'en', 'rss', 24, null, null, null, null, true),
  ('Lenny Newsletter', 'tech', 0.8, 'blog', true, 'https://www.lennysnewsletter.com/feed', 'https://lennysnewsletter.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Marginal Revolution', 'tech', 0.9, 'blog', true, 'https://feeds.feedburner.com/marginalrevolution/feed', 'https://marginalrevolution.com', 'en', 'rss', 24, null, null, null, null, true),
  ('MIT Technology Review', 'tech', 1, 'news', true, 'https://www.technologyreview.com/feed/', 'https://technologyreview.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Naval Ravikant', 'tech', 0.9, 'blog', true, 'https://nav.al/feed', 'https://nav.al', 'en', 'rss', 24, null, null, null, null, true),
  ('Not Boring', 'tech', 0.9, 'blog', true, 'https://www.notboring.co/feed', 'https://notboring.co', 'en', 'rss', 24, null, null, null, null, true),
  ('Paul Graham Essays', 'tech', 1, 'blog', true, 'http://www.paulgraham.com/rss.html', 'https://paulgraham.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Stratechery', 'tech', 1, 'blog', true, 'https://stratechery.com/feed/', 'https://stratechery.com', 'en', 'rss', 24, null, null, null, null, true),
  ('TechCrunch', 'tech', 1, 'news', true, 'https://techcrunch.com/feed/', 'https://techcrunch.com', 'en', 'rss', 24, null, null, null, null, true),
  ('The Generalist', 'tech', 0.9, 'blog', true, 'https://www.generalist.com/feed', 'https://generalist.com', 'en', 'rss', 24, null, null, null, null, true),
  ('The Verge', 'tech', 0.9, 'news', true, 'https://www.theverge.com/rss/index.xml', 'https://theverge.com', 'en', 'rss', 24, null, null, null, null, true),
  ('Wired', 'tech', 0.9, 'news', true, 'https://www.wired.com/feed/rss', 'https://wired.com', 'en', 'rss', 24, null, null, null, null, true),
  ('a16z crypto', 'vc', 1, 'vc_blog', true, 'https://a16zcrypto.com/feed', 'https://a16zcrypto.com', 'en', 'rss', 24, null, null, null, 'wed,sat', true),
  ('Andreessen Horowitz', 'vc', 1, 'vc_blog', true, 'https://a16z.com/feed/', 'https://a16z.com', 'en', 'rss', 24, null, null, null, 'wed,sat', true),
  ('Electric Capital', 'vc', 0.8, 'vc_blog', true, 'https://electriccapital.substack.com/feed', 'https://electriccapital.com', 'en', 'rss', 24, null, null, null, 'wed,sat', true),
  ('First Round Review', 'vc', 0.9, 'vc_blog', true, 'https://review.firstround.com/rss.xml', 'https://review.firstround.com', 'en', 'rss', 24, null, null, null, 'wed,sat', true),
  ('Sequoia Capital', 'vc', 1, 'vc_blog', true, 'https://www.sequoiacap.com/feed/', 'https://sequoiacap.com', 'en', 'rss', 24, null, null, null, 'wed,sat', true),
  ('Y Combinator Blog', 'vc', 1, 'vc_blog', true, 'https://www.ycombinator.com/blog/rss.xml', 'https://ycombinator.com/blog', 'en', 'rss', 24, null, null, null, 'wed,sat', true);
